# Generated by Django 3.1.3 on 2020-12-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paydotir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paydotir',
            name='trans',
        ),
        migrations.AddField(
            model_name='paydotir',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paydotir',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paydotir',
            name='transid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paydotir',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
